### ISSUE TITLE
Gallade is impossible to get

### ISSUE THREAD

**Issue by glacialcascade** [AdrianMarceau/pokebreed#2]
Even with appeals like +6 Fighting, +3 Psychic, and -1 Fairy (basically a powered down version of what others have managed to create) male Kirlias still do not evolve into Gallade.

**Comment by Plloi** [comment]
A possible fix for this could be to lower the level requirement for gallade so it can trigger before gardevoir and optionally remove gardevoir's type appeal.

**Comment by AdrianMarceau** [comment]
@Plloi This issue should already be fixed as of last night.  I went through and manually revamped all non-level-up evolution methods so they'd work better in the.  You can get both Gardevior and Gallade in the same run now with the following seed (~ Day 150):
``[PBS | Ralts ×1f/1m / Makuhita ×1f/1m / Meditite ×1f/1m / Lucario ×1f/2m / Ditto ×1 | v0.11.28]``
